language: python
python:
  - "3.6" # 3.6 development branch
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install codecov"
# command to run tests
script: "cd tests && pytest"
after_success: codecov
